"use client";

import { motion } from "framer-motion";
import {
  ArrowRight,
  Sparkles,
  Dumbbell,
  Brain,
  Target,
  Zap,
  Flame,
  MessageCircle,
  ChevronRight,
} from "lucide-react";
import Link from "next/link";
import { Navbar } from "@/components/layout/Navbar";
import { FloatingAIButton } from "@/components/layout/FloatingAIButton";
import { Button, Card, Badge } from "@/components/ui";
import { ScrollReveal } from "@/hooks/useScrollReveal";
import { images } from "@/data/images";

const features = [
  {
    icon: Brain,
    title: "AI Coach Mstfa",
    desc: "Personalized workout plans generated by AI based on your goals and level.",
    gradient: "from-[var(--color-accent)] to-blue-600",
    href: "/chat",
  },
  {
    icon: Dumbbell,
    title: "Exercise Library",
    desc: "100+ exercises with step-by-step instructions and visual guides.",
    gradient: "from-purple-500 to-pink-500",
    href: "/exercise-library",
  },
  {
    icon: Target,
    title: "Smart Generator",
    desc: "Structured weekly plans tailored to your age, weight, and goals.",
    gradient: "from-[var(--color-success)] to-emerald-600",
    href: "/workout-generator",
  },
  {
    icon: Zap,
    title: "Track Progress",
    desc: "Monitor streaks, calories, and your entire fitness journey.",
    gradient: "from-orange-500 to-red-500",
    href: "/dashboard",
  },
  {
    icon: Flame,
    title: "PDF Export",
    desc: "Download Apple-notes style workout plans for offline use.",
    gradient: "from-yellow-500 to-orange-500",
    href: "/workout-generator",
  },
  {
    icon: MessageCircle,
    title: "AI Chat",
    desc: "Get real answers from Mstfa — motivation, form tips, nutrition advice.",
    gradient: "from-teal-500 to-cyan-500",
    href: "/chat",
  },
];

const stats = [
  { value: "100+", label: "Exercises" },
  { value: "10K+", label: "Active Users" },
  { value: "50K+", label: "Workouts Done" },
  { value: "4.9", label: "App Rating" },
];

export default function HomePage() {
  return (
    <div className="min-h-screen bg-[var(--color-bg-primary)]">
      <Navbar />
      <FloatingAIButton />
      <main className="md:ml-[72px] lg:ml-[240px] pb-24 md:pb-8">
        {/* Hero Section */}
        <section className="relative min-h-[90vh] flex items-center justify-center overflow-hidden px-6">
          <div className="absolute inset-0 overflow-hidden pointer-events-none">
            <motion.div
              animate={{ scale: [1, 1.2, 1], rotate: [0, 180, 360] }}
              transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
              className="bg-orb orb-1 -top-40 -right-40"
            />
            <motion.div
              animate={{ scale: [1.2, 1, 1.2], rotate: [360, 180, 0] }}
              transition={{ duration: 25, repeat: Infinity, ease: "linear" }}
              className="bg-orb orb-2 -bottom-40 -left-40"
            />
            <motion.div
              animate={{ scale: [1, 1.1, 1], rotate: [0, -180, -360] }}
              transition={{ duration: 30, repeat: Infinity, ease: "linear" }}
              className="bg-orb orb-3 top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2"
            />
          </div>

          <div className="relative z-10 max-w-5xl mx-auto text-center">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, ease: [0.25, 0.1, 0.25, 1] }}
              className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass mb-8"
            >
              <Sparkles className="w-4 h-4 text-[var(--color-accent)]" />
              <span className="text-sm font-medium text-[var(--color-text-secondary)] font-[family-name:var(--font-sora)]">
                AI-Powered Fitness Coach
              </span>
            </motion.div>

            <motion.h1
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, delay: 0.1, ease: [0.25, 0.1, 0.25, 1] }}
              className="text-5xl md:text-7xl lg:text-8xl font-bold tracking-tight leading-[0.95] mb-6"
            >
              Train{" "}
              <span className="text-gradient">Smarter</span>
              <br />
              with{" "}
              <span className="text-gradient-warm">Mstfa</span>
            </motion.h1>

            <motion.p
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, delay: 0.2, ease: [0.25, 0.1, 0.25, 1] }}
              className="text-lg md:text-xl text-[var(--color-text-secondary)] max-w-2xl mx-auto mb-10 leading-relaxed"
            >
              Your personal AI fitness assistant that builds custom workout plans,
              guides your exercises, and keeps you motivated.
            </motion.p>

            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.7, delay: 0.3, ease: [0.25, 0.1, 0.25, 1] }}
              className="flex flex-col sm:flex-row items-center justify-center gap-4"
            >
              <Link href="/chat">
                <Button size="lg" className="group">
                  Chat with Mstfa
                  <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </Button>
              </Link>
              <Link href="/workout-generator">
                <Button variant="secondary" size="lg">
                  <Sparkles className="w-4 h-4" />
                  Generate Workout
                </Button>
              </Link>
            </motion.div>
          </div>
        </section>

        {/* Features Section */}
        <section className="px-6 py-24 max-w-6xl mx-auto">
          <ScrollReveal>
            <div className="text-center mb-16">
              <Badge variant="accent" className="mb-4">Features</Badge>
              <h2 className="text-3xl md:text-5xl font-bold tracking-tight mb-4">
                Everything you need to{" "}
                <span className="text-gradient">level up</span>
              </h2>
              <p className="text-[var(--color-text-secondary)] text-lg max-w-2xl mx-auto">
                A complete fitness ecosystem powered by AI, designed with
                Apple-level attention to detail.
              </p>
            </div>
          </ScrollReveal>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {features.map((feature, i) => (
              <ScrollReveal key={feature.title} delay={i * 0.05}>
                <Link href={feature.href}>
                  <Card className="h-full group">
                    <div
                      className={`w-12 h-12 rounded-xl bg-gradient-to-br ${feature.gradient} flex items-center justify-center mb-4 shadow-lg`}
                    >
                      <feature.icon className="w-6 h-6 text-white" />
                    </div>
                    <h3 className="text-lg font-bold font-[family-name:var(--font-space)] mb-2 flex items-center gap-2">
                      {feature.title}
                      <ArrowRight className="w-4 h-4 opacity-0 -translate-x-2 group-hover:opacity-100 group-hover:translate-x-0 transition-all duration-300" />
                    </h3>
                    <p className="text-sm text-[var(--color-text-secondary)] leading-relaxed">
                      {feature.desc}
                    </p>
                  </Card>
                </Link>
              </ScrollReveal>
            ))}
          </div>
        </section>

        {/* Stats Section */}
        <section className="px-6 py-24 max-w-6xl mx-auto">
          <ScrollReveal>
            <div className="glass rounded-3xl p-8 md:p-12">
              <div className="grid grid-cols-2 md:grid-cols-4 gap-8">
                {stats.map((stat, i) => (
                  <motion.div
                    key={stat.label}
                    initial={{ opacity: 0, y: 20 }}
                    whileInView={{ opacity: 1, y: 0 }}
                    viewport={{ once: true }}
                    transition={{ duration: 0.5, delay: i * 0.1 }}
                    className="text-center"
                  >
                    <div className="text-3xl md:text-4xl font-bold font-[family-name:var(--font-space)] tracking-tight mb-1">
                      {stat.value}
                    </div>
                    <div className="text-sm text-[var(--color-text-secondary)]">
                      {stat.label}
                    </div>
                  </motion.div>
                ))}
              </div>
            </div>
          </ScrollReveal>
        </section>

        {/* Preview Section */}
        <section className="px-6 py-24 max-w-6xl mx-auto">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
            <ScrollReveal direction="left">
              <div>
                <Badge variant="accent" className="mb-4">Preview</Badge>
                <h2 className="text-3xl md:text-5xl font-bold tracking-tight mb-4">
                  Your AI coach,{" "}
                  <span className="text-gradient-warm">always ready</span>
                </h2>
                <p className="text-[var(--color-text-secondary)] text-lg mb-6 leading-relaxed">
                  Mstfa understands your goals, tracks your progress, and adapts
                  your plan in real-time. No two workouts are the same.
                </p>
                <Link href="/chat">
                  <Button className="group">
                    Meet Mstfa
                    <ChevronRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                  </Button>
                </Link>
              </div>
            </ScrollReveal>

            <ScrollReveal direction="right">
              <div className="relative">
                <div className="rounded-3xl overflow-hidden glass p-1">
                  <div className="rounded-2xl overflow-hidden">
                    <img
                      src={images.hero.preview}
                      alt="Premium gym environment"
                      className="w-full aspect-video object-cover"
                    />
                    <div className="absolute inset-0 bg-gradient-to-t from-black/40 via-transparent to-transparent rounded-2xl" />
                  </div>
                </div>
                <motion.div
                  animate={{ y: [0, -10, 0] }}
                  transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
                  className="absolute -bottom-4 -right-4 glass rounded-2xl p-4 shadow-xl"
                >
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[var(--color-accent)] to-purple-600 flex items-center justify-center">
                      <Sparkles className="w-5 h-5 text-white" />
                    </div>
                    <div>
                      <p className="text-sm font-semibold font-[family-name:var(--font-space)]">AI Ready</p>
                      <p className="text-xs text-[var(--color-text-secondary)]">Plan generated</p>
                    </div>
                  </div>
                </motion.div>
              </div>
            </ScrollReveal>
          </div>
        </section>

        {/* CTA Section */}
        <section className="px-6 py-24 max-w-6xl mx-auto">
          <ScrollReveal>
            <div className="relative rounded-3xl overflow-hidden">
              <div className="absolute inset-0 bg-gradient-to-br from-[var(--color-accent)] via-purple-600 to-pink-500" />
              <div
                className="absolute inset-0 bg-cover bg-center opacity-20"
                style={{ backgroundImage: `url(${images.hero.cta})` }}
              />
              <div className="relative z-10 p-12 md:p-20 text-center text-white">
                <motion.div
                  initial={{ opacity: 0, scale: 0.8 }}
                  whileInView={{ opacity: 1, scale: 1 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: 0.2 }}
                  className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-white/20 backdrop-blur-sm mb-6"
                >
                  <Sparkles className="w-4 h-4" />
                  <span className="text-sm font-medium font-[family-name:var(--font-sora)]">
                    Start Your Journey
                  </span>
                </motion.div>

                <h2 className="text-3xl md:text-5xl font-bold font-[family-name:var(--font-space)] tracking-tight mb-4">
                  Ready to transform?
                </h2>
                <p className="text-lg text-white/80 max-w-xl mx-auto mb-8">
                  Join thousands training smarter with Mstfa AI.
                </p>

                <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                  <Link href="/chat">
                    <Button className="bg-white text-[var(--color-accent)] hover:bg-white/90 shadow-xl group">
                      Get Started Free
                      <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                    </Button>
                  </Link>
                  <Link href="/exercise-library">
                    <Button variant="ghost" className="text-white hover:bg-white/10">
                      Browse Exercises
                    </Button>
                  </Link>
                </div>
              </div>
            </div>
          </ScrollReveal>
        </section>

        {/* Footer */}
        <footer className="px-6 py-12 max-w-6xl mx-auto text-center text-sm text-[var(--color-text-tertiary)]">
          <div className="flex items-center justify-center gap-2 mb-4">
            <Dumbbell className="w-4 h-4" />
            <span className="font-semibold font-[family-name:var(--font-space)]">MustafaMoves</span>
          </div>
          <p>AI-Powered Fitness. Made with intensity.</p>
        </footer>
      </main>
    </div>
  );
}
