"use client";

import { useEffect, useRef, useState } from "react";
import { motion, useScroll, useTransform, AnimatePresence } from "framer-motion";
import {
  ArrowRight,
  Dumbbell,
  Brain,
  Target,
  Zap,
  Flame,
  MessageCircle,
  Sparkles,
  ChevronRight,
  Bot,
  X,
  BarChart3,
  FileDown,
  MessageSquare,
} from "lucide-react";
import Link from "next/link";
import { Navbar } from "@/components/layout/Navbar";
import { FloatingAIButton } from "@/components/layout/FloatingAIButton";

const features = [
  {
    icon: Brain,
    title: "AI Coach Mstfa",
    desc: "Personalized workout plans generated by AI based on your goals and level.",
    href: "/chat",
    detail: "Mstfa is your personal AI fitness coach. Tell it your goals — muscle gain, fat loss, strength — and it creates a custom plan just for you. Ask questions, get form tips, nutrition advice, and motivation anytime.",
    bullets: ["AI-generated workout plans", "Real-time form feedback", "Nutrition & diet advice", "24/7 motivation & support"],
  },
  {
    icon: Dumbbell,
    title: "Exercise Library",
    desc: "100+ exercises with step-by-step instructions and visual guides.",
    href: "/exercise-library",
    detail: "Browse 100+ exercises with detailed instructions, target muscles, difficulty levels, and proper form guidance. Filter by muscle group, difficulty, or search by name.",
    bullets: ["100+ exercises with guides", "Filter by muscle group", "Difficulty ratings", "Sets, reps & rest info"],
  },
  {
    icon: Target,
    title: "Smart Generator",
    desc: "Structured weekly plans tailored to your age, weight, and goals.",
    href: "/workout-generator",
    detail: "Enter your age, weight, height, fitness level, and goal. Mstfa's AI generates a complete weekly workout plan with exercises, sets, reps, and rest periods — all personalized to you.",
    bullets: ["Personalized weekly plans", "Age/weight/height tailored", "Goal-specific workouts", "Export to PDF"],
  },
  {
    icon: Zap,
    title: "Track Progress",
    desc: "Monitor streaks, calories, and your entire fitness journey.",
    href: "/dashboard",
    detail: "Your dashboard shows your workout history, streak, calories burned, and more. See your weekly activity at a glance and get AI-powered recommendations from Mstfa.",
    bullets: ["Workout history log", "Streak tracking", "Calorie monitoring", "AI recommendations"],
  },
  {
    icon: Flame,
    title: "PDF Export",
    desc: "Download Apple-notes style workout plans for offline use.",
    href: "/workout-generator",
    detail: "Export any generated workout plan as a clean PDF document. Take your plan to the gym without needing your phone. Perfect for offline training.",
    bullets: ["Clean PDF format", "All exercises included", "Take to the gym offline", "Share with friends"],
  },
  {
    icon: MessageCircle,
    title: "AI Chat",
    desc: "Get real answers from Mstfa — motivation, form tips, nutrition advice.",
    href: "/chat",
    detail: "Chat directly with Mstfa AI about anything fitness. Need a quick form check? Wondering what to eat post-workout? Want a motivational boost? Just ask.",
    bullets: ["Real-time AI chat", "Fitness form guidance", "Nutrition & meal tips", "Motivation on demand"],
  },
];

const stats = [
  { value: "100+", label: "Exercises" },
  { value: "10K+", label: "Active Users" },
  { value: "50K+", label: "Workouts Done" },
  { value: "4.9", label: "App Rating" },
];

function useRevealOnScroll() {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);
  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) { setVisible(true); observer.disconnect(); } },
      { threshold: 0.1 }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, []);
  return { ref, visible };
}

function RevealSection({ children, className = "", delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  const { ref, visible } = useRevealOnScroll();
  return (
    <div
      ref={ref}
      className={className}
      style={{
        opacity: visible ? 1 : 0,
        transform: visible ? "translateY(0)" : "translateY(40px)",
        transitionDelay: `${delay}s`,
        transitionDuration: "0.8s",
        transitionTimingFunction: "cubic-bezier(0.25, 0.1, 0.25, 1)",
      }}
    >
      {children}
    </div>
  );
}

export default function HomePage() {
  const { scrollYProgress } = useScroll();
  const heroOpacity = useTransform(scrollYProgress, [0, 0.12], [1, 0]);
  const heroScale = useTransform(scrollYProgress, [0, 0.12], [1, 0.95]);
  const [selectedFeature, setSelectedFeature] = useState<typeof features[number] | null>(null);

  const tickerItems = [
    "AI-POWERED FITNESS", "TRAIN SMARTER", "NO CAP", "LET'S GET IT",
    "MSTFA AI COACH", "BUILD MUSCLE", "LOSE FAT", "STAY STRONG",
    "AI-POWERED FITNESS", "TRAIN SMARTER", "NO CAP", "LET'S GET IT",
    "MSTFA AI COACH", "BUILD MUSCLE", "LOSE FAT", "STAY STRONG",
  ];

  return (
    <div className="min-h-screen bg-[var(--color-bg-primary)]">
      <Navbar />
      <FloatingAIButton />

      {/* Hero — Kerna.studio exact style */}
      <motion.section
        style={{ opacity: heroOpacity, scale: heroScale }}
        className="h-screen flex flex-col justify-center items-center px-6 relative overflow-hidden"
      >
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[900px] h-[900px] rounded-full bg-[var(--color-accent)]/4 blur-[200px] pointer-events-none" />

        <div className="text-center max-w-4xl mx-auto relative z-10 flex flex-col items-center gap-[30px] md:gap-[30px]">
          {/* Logo area — like Kerna's SVG logo */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, ease: [0.25, 0.1, 0.25, 1] }}
            className="flex items-center gap-3"
          >
            <div className="w-10 h-10 rounded-[var(--radius-md)] bg-[var(--color-accent)] flex items-center justify-center">
              <Dumbbell className="w-5 h-5 text-[#0d0d0d]" />
            </div>
            <span className="text-xl font-[600] tracking-tight">MustafaMoves</span>
          </motion.div>

          {/* Heading with staggered text — like Kerna's c-appear */}
          <h1 className="max-w-[710px]">
            <span className="block overflow-hidden">
              <motion.span
                initial={{ opacity: 0, y: 40 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.7, delay: 0.2, ease: [0.25, 0.1, 0.25, 1] }}
                className="block text-[clamp(32px,5.5vw,64px)] font-[600] tracking-[-0.04em] leading-[1.08]"
              >
                Transform your fitness
              </motion.span>
            </span>
            <span className="block overflow-hidden mt-1">
              <motion.span
                initial={{ opacity: 0, y: 40 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.7, delay: 0.35, ease: [0.25, 0.1, 0.25, 1] }}
                className="block text-[clamp(32px,5.5vw,64px)] font-[600] tracking-[-0.04em] leading-[1.08]"
              >
                into a{" "}
                <span className="text-[var(--color-accent)] font-[600] tracking-[-0.04em] leading-[93%]">
                  charismatic journey
                </span>
              </motion.span>
            </span>
          </h1>

          {/* CTA — like Kerna's c-button */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6, delay: 0.6, ease: [0.25, 0.1, 0.25, 1] }}
          >
            <Link
              href="/chat"
              className="inline-flex items-center gap-2 px-7 py-3 rounded-full bg-[var(--color-accent)] text-[#0d0d0d] font-[600] text-sm hover:bg-[var(--color-accent-hover)] transition-all duration-300"
            >
              Chat with Mstfa
              <ArrowRight className="w-4 h-4" />
            </Link>
          </motion.div>
        </div>
      </motion.section>

      {/* Marquee Ticker */}
      <div className="marquee border-y border-[var(--color-border)] py-4 md:py-5">
        <div className="marquee-track">
          {tickerItems.map((item, i) => (
            <span key={i} className="text-[clamp(14px,2vw,20px)] font-[600] tracking-[0.15em] text-white/10 px-8 uppercase">
              {item}
              <span className="text-[var(--color-accent)] ml-8">✦</span>
            </span>
          ))}
        </div>
      </div>

      {/* Features Grid — clickable cards with modal */}
      <section className="section-padding max-w-6xl mx-auto">
        <RevealSection>
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-5xl font-[600] tracking-tight">
              Everything you need to{" "}
              <span className="text-[var(--color-accent)]">level up</span>
            </h2>
            <p className="text-[var(--color-text-secondary)] text-lg max-w-2xl mx-auto mt-4">
              A complete fitness ecosystem powered by AI, designed to keep you going — no cap.
            </p>
          </div>
        </RevealSection>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
          {features.map((feature, i) => (
            <RevealSection key={feature.title} delay={i * 0.05}>
              <button
                onClick={() => setSelectedFeature(feature)}
                className="w-full text-left p-6 md:p-8 rounded-[var(--radius-lg)] bg-card hover:bg-[var(--color-surface-hover)] hover:border-[var(--color-border-strong)] transition-all duration-300 group h-full cursor-pointer"
              >
                <div className="w-10 h-10 rounded-[var(--radius-md)] bg-[var(--color-accent-soft)] flex items-center justify-center mb-4">
                  <feature.icon className="w-5 h-5 text-[var(--color-accent)]" />
                </div>
                <h3 className="text-lg font-[600] mb-2 flex items-center gap-2">
                  {feature.title}
                  <ArrowRight className="w-4 h-4 opacity-0 -translate-x-2 group-hover:opacity-100 group-hover:translate-x-0 transition-all duration-300 text-[var(--color-accent)]" />
                </h3>
                <p className="text-sm text-[var(--color-text-secondary)] leading-relaxed">
                  {feature.desc}
                </p>
              </button>
            </RevealSection>
          ))}
        </div>
      </section>

      {/* Feature Detail Modal */}
      <AnimatePresence>
        {selectedFeature && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-[100] bg-black/60 backdrop-blur-sm flex items-end md:items-center justify-center p-0 md:p-6"
            onClick={() => setSelectedFeature(null)}
          >
            <motion.div
              initial={{ y: "100%", opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              exit={{ y: "100%", opacity: 0 }}
              transition={{ type: "spring", damping: 25, stiffness: 200 }}
              onClick={(e) => e.stopPropagation()}
              className="w-full md:max-w-lg bg-[var(--color-bg-primary)] border border-[var(--color-border)] rounded-t-3xl md:rounded-3xl max-h-[85vh] overflow-y-auto"
            >
              <div className="p-6 md:p-8">
                {/* Close */}
                <button
                  onClick={() => setSelectedFeature(null)}
                  className="absolute top-4 right-4 w-8 h-8 rounded-full bg-[var(--color-bg-tertiary)] flex items-center justify-center text-[var(--color-text-secondary)] hover:text-[var(--color-text-primary)] transition-colors"
                >
                  <X className="w-4 h-4" />
                </button>

                {/* Icon + Title */}
                <div className="flex items-center gap-4 mb-6">
                  <div className="w-14 h-14 rounded-[var(--radius-lg)] bg-[var(--color-accent-soft)] flex items-center justify-center">
                    <selectedFeature.icon className="w-7 h-7 text-[var(--color-accent)]" />
                  </div>
                  <div>
                    <h2 className="text-2xl font-[600]">{selectedFeature.title}</h2>
                    <p className="text-sm text-[var(--color-text-secondary)]">{selectedFeature.desc}</p>
                  </div>
                </div>

                {/* Detail */}
                <p className="text-sm text-[var(--color-text-secondary)] leading-relaxed mb-6">
                  {selectedFeature.detail}
                </p>

                {/* Bullets */}
                <div className="space-y-3 mb-8">
                  {selectedFeature.bullets.map((bullet, i) => (
                    <motion.div
                      key={bullet}
                      initial={{ opacity: 0, x: -10 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: i * 0.08 }}
                      className="flex items-center gap-3"
                    >
                      <div className="w-1.5 h-1.5 rounded-full bg-[var(--color-accent)]" />
                      <span className="text-sm text-[var(--color-text-primary)]">{bullet}</span>
                    </motion.div>
                  ))}
                </div>

                {/* CTA */}
                <Link
                  href={selectedFeature.href}
                  onClick={() => setSelectedFeature(null)}
                  className="w-full py-3.5 rounded-[var(--radius-lg)] bg-[var(--color-accent)] text-[#0d0d0d] font-[600] text-sm hover:bg-[var(--color-accent-hover)] transition-all inline-flex items-center justify-center gap-2"
                >
                  Go to {selectedFeature.title}
                  <ArrowRight className="w-4 h-4" />
                </Link>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Stats */}
      <section className="section-padding max-w-6xl mx-auto">
        <RevealSection>
          <div className="bg-card rounded-[var(--radius-2xl)] p-8 md:p-16">
            <div className="grid grid-cols-2 md:grid-cols-4 gap-8 md:gap-12">
              {stats.map((stat, i) => (
                <motion.div
                  key={stat.label}
                  initial={{ opacity: 0, y: 20 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.5, delay: i * 0.1 }}
                  className="text-center"
                >
                  <div className="text-4xl md:text-5xl font-[600] tracking-tight mb-1 text-[var(--color-accent)]">
                    {stat.value}
                  </div>
                  <div className="text-sm text-[var(--color-text-secondary)]">
                    {stat.label}
                  </div>
                </motion.div>
              ))}
            </div>
          </div>
        </RevealSection>
      </section>

      {/* AI Coach Preview */}
      <section className="section-padding max-w-6xl mx-auto">
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 md:gap-16 items-center">
          <RevealSection>
            <div>
              <p className="text-sm text-[var(--color-accent)] font-[500] tracking-[0.15em] uppercase mb-4">Preview</p>
              <h2 className="text-3xl md:text-5xl font-[600] tracking-tight mb-4">
                Your AI coach,{" "}
                <span className="text-[var(--color-accent)]">always ready</span>
              </h2>
              <p className="text-[var(--color-text-secondary)] text-lg mb-6 leading-relaxed">
                Mstfa understands your goals, tracks your progress, and adapts your plan in real-time.
              </p>
              <Link
                href="/chat"
                className="group inline-flex items-center gap-2 text-sm font-[600] text-[var(--color-accent)] hover:text-[var(--color-accent-hover)] transition-colors"
              >
                Meet Mstfa
                <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </Link>
            </div>
          </RevealSection>

          <RevealSection delay={0.15}>
            <div className="relative">
              <div className="bg-card rounded-[var(--radius-2xl)] overflow-hidden">
                <div className="aspect-[4/3] bg-gradient-to-br from-[var(--color-accent-soft)] to-transparent flex items-center justify-center">
                  <Bot className="w-24 h-24 text-[var(--color-accent)]/30" />
                </div>
                <div className="absolute inset-0 bg-gradient-to-t from-[#0d0d0d] via-transparent to-transparent rounded-[var(--radius-2xl)]" />
              </div>
              <motion.div
                animate={{ y: [0, -8, 0] }}
                transition={{ duration: 4, repeat: Infinity, ease: "easeInOut" }}
                className="absolute -bottom-4 -right-4 bg-[var(--color-bg-secondary)] border border-[var(--color-border)] rounded-[var(--radius-lg)] p-4 shadow-xl"
              >
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-[var(--radius-md)] bg-[var(--color-accent-soft)] flex items-center justify-center">
                    <Sparkles className="w-5 h-5 text-[var(--color-accent)]" />
                  </div>
                  <div>
                    <p className="text-sm font-[600]">AI Ready</p>
                    <p className="text-xs text-[var(--color-text-secondary)]">Plan generated</p>
                  </div>
                </div>
              </motion.div>
            </div>
          </RevealSection>
        </div>
      </section>

      {/* Process / Steps */}
      <section className="section-padding max-w-6xl mx-auto">
        <RevealSection>
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-5xl font-[600] tracking-tight">
              How it{" "}
              <span className="text-[var(--color-accent)]">works</span>
            </h2>
            <p className="text-[var(--color-text-secondary)] text-lg max-w-2xl mx-auto mt-4">Four simple steps to transform your fitness journey.</p>
          </div>
        </RevealSection>

        <div className="space-y-4">
          {[
            { num: "01", title: "Tell Mstfa your goals", desc: "Share your fitness level, age, weight, and what you want to achieve." },
            { num: "02", title: "Get your AI plan", desc: "Mstfa generates a personalized weekly workout plan tailored to you." },
            { num: "03", title: "Train & track", desc: "Follow your plan, log workouts, and watch your progress grow." },
            { num: "04", title: "Level up", desc: "Mstfa adapts your plan as you get stronger. Keep progressing." },
          ].map((step, i) => (
            <RevealSection key={step.num} delay={i * 0.08}>
              <div className="bg-card rounded-[var(--radius-xl)] p-6 md:p-8 flex items-start gap-6 md:gap-8 group hover:bg-[var(--color-surface-hover)] transition-all duration-300">
                <div className="text-[clamp(40px,5vw,72px)] font-[700] text-[var(--color-accent)] leading-none opacity-40 group-hover:opacity-70 transition-opacity">
                  {step.num}
                </div>
                <div className="flex-1 pt-2">
                  <h3 className="text-lg md:text-xl font-[600] mb-1">{step.title}</h3>
                  <p className="text-sm text-[var(--color-text-secondary)]">{step.desc}</p>
                </div>
                <ChevronRight className="w-5 h-5 text-[var(--color-text-tertiary)] mt-3 opacity-0 group-hover:opacity-100 transition-opacity flex-shrink-0" />
              </div>
            </RevealSection>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="section-padding max-w-6xl mx-auto">
        <RevealSection>
          <div className="relative rounded-[var(--radius-2xl)] overflow-hidden bg-[var(--color-accent)]">
            <div className="absolute inset-0 bg-gradient-to-br from-[var(--color-accent)] via-[var(--color-accent-hover)] to-[var(--color-accent)] opacity-50" />
            <div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_50%,rgba(255,255,255,0.1)_0%,transparent_60%)]" />
            <div className="relative z-10 p-12 md:p-20 text-center">
              <h2 className="text-3xl md:text-5xl font-[600] tracking-tight text-[#0d0d0d] mb-4">Ready to transform?</h2>
              <p className="text-lg text-[#0d0d0d]/70 max-w-xl mx-auto mb-8">Join thousands training smarter with Mstfa AI — no cap.</p>
              <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
                <Link href="/chat" className="inline-flex items-center gap-2 px-8 py-3.5 rounded-full bg-[#0d0d0d] text-white font-[600] text-sm hover:bg-[#1a1a1a] transition-all duration-300">
                  Get Started Free
                  <ArrowRight className="w-4 h-4" />
                </Link>
                <Link href="/exercise-library" className="inline-flex items-center gap-2 px-8 py-3.5 rounded-full bg-white/20 text-[#0d0d0d] font-[500] text-sm hover:bg-white/30 transition-all duration-300">
                  Browse Exercises
                </Link>
              </div>
            </div>
          </div>
        </RevealSection>
      </section>

      {/* Footer */}
      <footer className="section-padding max-w-6xl mx-auto text-center">
        <div className="flex items-center justify-center gap-2 mb-4">
          <Dumbbell className="w-4 h-4 text-[var(--color-accent)]" />
          <span className="font-[600]">MustafaMoves</span>
        </div>
        <p className="text-sm text-[var(--color-text-secondary)]">AI-Powered Fitness. Made with intensity.</p>
      </footer>
    </div>
  );
}
