"use client";

import { motion } from "framer-motion";
import { Dumbbell, Brain, Target, Zap, ArrowRight, Flame } from "lucide-react";
import Link from "next/link";
import { Card } from "@/components/ui";

const features = [
  {
    icon: Brain,
    title: "AI Coach Mstfa",
    description: "Get personalized workout plans generated by our AI fitness assistant based on your goals and level.",
    gradient: "from-[var(--color-accent)] to-blue-600",
    href: "/chat",
  },
  {
    icon: Dumbbell,
    title: "Exercise Library",
    description: "Explore 100+ exercises with step-by-step instructions, target muscles, and visual demonstrations.",
    gradient: "from-purple-500 to-pink-500",
    href: "/exercise-library",
  },
  {
    icon: Target,
    title: "Workout Generator",
    description: "Generate structured weekly workout plans tailored to your age, weight, and fitness goals.",
    gradient: "from-[var(--color-success)] to-emerald-600",
    href: "/workout-generator",
  },
  {
    icon: Flame,
    title: "Track Progress",
    description: "Monitor your workout streak, calories burned, and overall fitness journey on your dashboard.",
    gradient: "from-orange-500 to-red-500",
    href: "/dashboard",
  },
  {
    icon: Zap,
    title: "PDF Export",
    description: "Download clean, structured workout plans in Apple Notes-style PDF format for offline use.",
    gradient: "from-yellow-500 to-orange-500",
    href: "/workout-generator",
  },
];

const container = {
  hidden: { opacity: 0 },
  show: {
    opacity: 1,
    transition: { staggerChildren: 0.1 },
  },
};

const item = {
  hidden: { opacity: 0, y: 30 },
  show: { opacity: 1, y: 0 },
};

export function FeaturesSection() {
  return (
    <section className="px-6 py-24 max-w-6xl mx-auto">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: "-100px" }}
        transition={{ duration: 0.6 }}
        className="text-center mb-16"
      >
        <h2 className="text-3xl md:text-5xl font-bold tracking-tight mb-4">
          Everything you need to{" "}
          <span className="text-gradient">level up</span>
        </h2>
        <p className="text-[var(--color-text-secondary)] text-lg max-w-2xl mx-auto">
          A complete fitness ecosystem powered by AI, designed with Apple-level attention to detail.
        </p>
      </motion.div>

      <motion.div
        variants={container}
        initial="hidden"
        whileInView="show"
        viewport={{ once: true, margin: "-100px" }}
        className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4"
      >
        {features.map((feature) => (
          <motion.div key={feature.title} variants={item}>
            <Link href={feature.href}>
              <Card className="h-full group">
                <div className={`w-12 h-12 rounded-[var(--radius-lg)] bg-gradient-to-br ${feature.gradient} flex items-center justify-center mb-4`}>
                  <feature.icon className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-lg font-semibold mb-2 flex items-center gap-2">
                  {feature.title}
                  <ArrowRight className="w-4 h-4 opacity-0 -translate-x-2 group-hover:opacity-100 group-hover:translate-x-0 transition-all duration-300" />
                </h3>
                <p className="text-sm text-[var(--color-text-secondary)] leading-relaxed">
                  {feature.description}
                </p>
              </Card>
            </Link>
          </motion.div>
        ))}
      </motion.div>
    </section>
  );
}
