"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Sparkles,
  Download,
  RotateCcw,
  ChevronRight,
  Dumbbell,
  Calendar,
  ArrowLeft,
} from "lucide-react";
import Link from "next/link";
import { Navbar } from "@/components/layout/Navbar";
import { FloatingAIButton } from "@/components/layout/FloatingAIButton";
import { Button, Card, Badge, Input } from "@/components/ui";
import { useAuth } from "@/hooks/useAuth";
import {
  workoutGoals,
  fitnessLevels,
  generateWorkoutPlan,
  WorkoutPlan,
} from "@/data/exercises";

export default function WorkoutGeneratorPage() {
  const { profile } = useAuth();
  const [step, setStep] = useState(0);
  const [age, setAge] = useState(String(profile?.age || 25));
  const [weight, setWeight] = useState(String(profile?.weight || 70));
  const [height, setHeight] = useState(String(profile?.height || 175));
  const [goal, setGoal] = useState(profile?.goal || "muscle");
  const [level, setLevel] = useState(profile?.level || "intermediate");
  const [plan, setPlan] = useState<WorkoutPlan | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = () => {
    setIsGenerating(true);
    setTimeout(() => {
      const newPlan = generateWorkoutPlan(
        parseInt(age),
        parseFloat(weight),
        parseFloat(height),
        goal,
        level
      );
      setPlan(newPlan);
      setIsGenerating(false);
      setStep(2);
    }, 2000);
  };

  const handleDownloadPDF = async () => {
    if (!plan) return;
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF();

    doc.setFontSize(28);
    doc.setFont("helvetica", "bold");
    doc.text("MustafaMoves", 20, 25);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 120, 120);
    doc.text("AI-Powered Workout Plan", 20, 33);
    doc.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 40);

    doc.setDrawColor(200, 200, 200);
    doc.line(20, 45, 190, 45);

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text(`${plan.name}`, 20, 55);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Goal: ${plan.goal.charAt(0).toUpperCase() + plan.goal.slice(1).replace("-", " ")}`,
      20,
      63
    );
    doc.text(
      `Level: ${plan.level.charAt(0).toUpperCase() + plan.level.slice(1)}`,
      20,
      70
    );

    let y = 85;
    plan.days.forEach((day) => {
      if (y > 250) {
        doc.addPage();
        y = 20;
      }
      if (day.isRestDay) {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(100, 100, 100);
        doc.text(`${day.day} — Rest Day`, 20, y);
        y += 12;
      } else {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(0, 0, 0);
        doc.text(`${day.day} — ${day.focus}`, 20, y);
        y += 8;
        day.exercises.forEach((exercise) => {
          if (y > 270) {
            doc.addPage();
            y = 20;
          }
          doc.setFontSize(10);
          doc.setFont("helvetica", "normal");
          doc.setTextColor(60, 60, 60);
          doc.text(`• ${exercise.name}`, 28, y);
          doc.text(`${exercise.sets} sets × ${exercise.reps} reps`, 140, y);
          y += 6;
        });
        y += 6;
      }
    });

    if (y > 230) {
      doc.addPage();
      y = 20;
    }
    y += 5;
    doc.setDrawColor(200, 200, 200);
    doc.line(20, y, 190, y);
    y += 10;
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(0, 0, 0);
    doc.text("Training Tips", 20, y);
    y += 8;
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(80, 80, 80);
    const tips = [
      "Always warm up 5-10 minutes before training",
      "Focus on progressive overload each week",
      "Get 7-9 hours of sleep for optimal recovery",
      "Stay hydrated — aim for 3-4 liters daily",
      "Fuel your workouts with proper nutrition",
    ];
    tips.forEach((tip) => {
      doc.text(`• ${tip}`, 28, y);
      y += 6;
    });
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by MustafaMoves — AI-Powered Fitness", 20, 285);
    doc.save(`MustafaMoves-${plan.name.replace(/\s+/g, "-")}.pdf`);
  };

  return (
    <div className="min-h-screen bg-[var(--color-bg-primary)]">
      <Navbar />
      <FloatingAIButton />
      <main className="md:ml-[72px] lg:ml-[240px] pb-24 md:pb-8">
        <div className="px-6 py-6 flex items-center gap-4">
          <Link href="/" className="md:hidden">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <div>
            <h1 className="text-2xl font-bold font-[family-name:var(--font-space)] tracking-tight">
              Workout Generator
            </h1>
            <p className="text-sm text-[var(--color-text-secondary)]">
              AI-powered personalized workout plans
            </p>
          </div>
        </div>

        <div className="px-6 max-w-4xl mx-auto">
          <AnimatePresence mode="wait">
            {step === 0 && (
              <motion.div
                key="step0"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.4 }}
              >
                <Card glass className="mb-6">
                  <div className="flex items-center gap-3 mb-6">
                    <div className="w-10 h-10 rounded-xl bg-[var(--color-accent)]/10 flex items-center justify-center">
                      <Dumbbell className="w-5 h-5 text-[var(--color-accent)]" />
                    </div>
                    <div>
                      <h2 className="font-semibold font-[family-name:var(--font-space)]">
                        Personal Details
                      </h2>
                      <p className="text-xs text-[var(--color-text-secondary)]">
                        Help Mstfa understand your body
                      </p>
                    </div>
                  </div>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
                    <Input label="Age" type="number" value={age} onChange={setAge} placeholder="25" />
                    <Input label="Weight (kg)" type="number" value={weight} onChange={setWeight} placeholder="70" />
                    <Input label="Height (cm)" type="number" value={height} onChange={setHeight} placeholder="175" />
                  </div>
                  <Button onClick={() => setStep(1)} className="w-full">
                    Continue
                    <ChevronRight className="w-4 h-4" />
                  </Button>
                </Card>
              </motion.div>
            )}

            {step === 1 && (
              <motion.div
                key="step1"
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.4 }}
              >
                <Card glass className="mb-6">
                  <h2 className="font-semibold font-[family-name:var(--font-space)] mb-4">
                    What&apos;s your goal?
                  </h2>
                  <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-6">
                    {workoutGoals.map((g) => (
                      <motion.button
                        key={g.id}
                        whileHover={{ scale: 1.02 }}
                        whileTap={{ scale: 0.98 }}
                        onClick={() => setGoal(g.id)}
                        className={`p-4 rounded-xl text-left transition-all duration-300 ${
                          goal === g.id
                            ? "bg-[var(--color-accent)]/10 border-2 border-[var(--color-accent)]"
                            : "bg-[var(--color-bg-tertiary)] border-2 border-transparent hover:border-[var(--color-border-strong)]"
                        }`}
                      >
                        <div className="text-2xl mb-2">{g.icon}</div>
                        <div className="font-medium text-sm">{g.label}</div>
                        <div className="text-xs text-[var(--color-text-secondary)] mt-1">
                          {g.description}
                        </div>
                      </motion.button>
                    ))}
                  </div>

                  <h2 className="font-semibold font-[family-name:var(--font-space)] mb-4">
                    Fitness Level
                  </h2>
                  <div className="flex gap-3 mb-6">
                    {fitnessLevels.map((l) => (
                      <motion.button
                        key={l.id}
                        whileHover={{ scale: 1.02 }}
                        whileTap={{ scale: 0.98 }}
                        onClick={() => setLevel(l.id)}
                        className={`flex-1 p-3 rounded-xl text-center transition-all duration-300 ${
                          level === l.id
                            ? "bg-[var(--color-accent)]/10 border-2 border-[var(--color-accent)]"
                            : "bg-[var(--color-bg-tertiary)] border-2 border-transparent"
                        }`}
                      >
                        <div className="font-medium text-sm capitalize">{l.label}</div>
                      </motion.button>
                    ))}
                  </div>

                  <div className="flex gap-3">
                    <Button variant="secondary" onClick={() => setStep(0)} className="flex-1">
                      Back
                    </Button>
                    <Button onClick={handleGenerate} className="flex-1" disabled={isGenerating}>
                      {isGenerating ? (
                        <motion.div
                          animate={{ rotate: 360 }}
                          transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                        >
                          <Sparkles className="w-4 h-4" />
                        </motion.div>
                      ) : (
                        <>
                          <Sparkles className="w-4 h-4" />
                          Generate Plan
                        </>
                      )}
                    </Button>
                  </div>
                </Card>
              </motion.div>
            )}

            {step === 2 && plan && (
              <motion.div
                key="step2"
                initial={{ opacity: 0, scale: 0.95 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ duration: 0.5 }}
              >
                <Card glass className="mb-6">
                  <div className="flex items-center justify-between mb-6">
                    <div>
                      <h2 className="text-xl font-bold font-[family-name:var(--font-space)]">
                        {plan.name}
                      </h2>
                      <p className="text-sm text-[var(--color-text-secondary)]">
                        {plan.days.filter((d) => !d.isRestDay).length} training days •{" "}
                        {plan.level}
                      </p>
                    </div>
                    <div className="flex gap-2">
                      <Button variant="secondary" size="sm" onClick={handleDownloadPDF}>
                        <Download className="w-4 h-4" />
                        PDF
                      </Button>
                      <Button variant="ghost" size="sm" onClick={() => setStep(0)}>
                        <RotateCcw className="w-4 h-4" />
                      </Button>
                    </div>
                  </div>

                  <div className="space-y-3">
                    {plan.days.map((day, i) => (
                      <motion.div
                        key={day.day}
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.3, delay: i * 0.05 }}
                        className={`p-4 rounded-xl ${
                          day.isRestDay
                            ? "bg-[var(--color-bg-tertiary)]/50"
                            : "bg-[var(--color-bg-tertiary)] border border-[var(--color-border)]"
                        }`}
                      >
                        <div className="flex items-center justify-between mb-2">
                          <div className="flex items-center gap-3">
                            <Calendar className="w-4 h-4 text-[var(--color-text-tertiary)]" />
                            <span className="font-medium text-sm">{day.day}</span>
                          </div>
                          <Badge variant={day.isRestDay ? "default" : "accent"}>
                            {day.isRestDay ? "Rest" : day.focus}
                          </Badge>
                        </div>
                        {!day.isRestDay && (
                          <div className="space-y-2 mt-3">
                            {day.exercises.map((exercise) => (
                              <div
                                key={exercise.id}
                                className="flex items-center justify-between text-xs text-[var(--color-text-secondary)]"
                              >
                                <span>{exercise.name}</span>
                                <span className="font-mono">
                                  {exercise.sets}×{exercise.reps}
                                </span>
                              </div>
                            ))}
                          </div>
                        )}
                      </motion.div>
                    ))}
                  </div>
                </Card>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </main>
    </div>
  );
}
